### ISSUE TITLE
不能设置保留小数点后几位么？

### ISSUE THREAD

**Issue by daolou** [soda-x/postcss-plugin-px2rem#17]
如题

**Comment by soda-x** [comment]
同 https://github.com/pigcan/postcss-plugin-px2rem/issues/12 ，@Mr-jiangzhiguo 这个暂时就关闭了，可以一起来看看怎么解决好

**Comment by daolou** [comment]
> 同 #12 ，@Mr-jiangzhiguo 这个暂时就关闭了，可以一起来看看怎么解决好

我其实是想设置最终转为px时，保留几位小数，我遇到的问题是，在dpr=2的375手机上表现正常（图1），在其他的上面不正常（图2），我估摸着是不太精确导致的，所以想多几位，让肉眼看不出来就行了。
![image1](https://user-images.githubusercontent.com/22312092/69413287-7d0e0300-0d4b-11ea-8510-cb3e0c169e85.png)

![image2](https://user-images.githubusercontent.com/22312092/69413397-b0509200-0d4b-11ea-989d-0af438e8aeab.png)

**Comment by daolou** [comment]
我换了一种解决方案，每个小块左右两边给了一个-1px的margin
